/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pjs.wafapp;

import com.pjs.wafapp.dao.BlockCidrDao;
import com.pjs.wafapp.dao.BlockFqdnDao;
import com.pjs.wafapp.dao.WebServerDao;
import com.pjs.wafapp.dao.mysql.BlockCidrDaoImpl;
import com.pjs.wafapp.dao.mysql.BlockFqdnDaoImpl;
import com.pjs.wafapp.dao.mysql.WebServerDaoImpl;
import com.pjs.wafapp.handler.blockcidr.BlockCidrAddHandler;
import com.pjs.wafapp.handler.blockcidr.BlockCidrDeleteHandler;
import com.pjs.wafapp.handler.blockcidr.BlockCidrListHandler;
import com.pjs.wafapp.handler.blockcidr.BlockCidrModifyHandler;
import com.pjs.wafapp.handler.blockcidr.BlockCidrViewHandler;
import com.pjs.menu.MenuGroup;
import com.pjs.util.Prompt;
import com.pjs.wafapp.handler.blockfqdn.BlockFqdnAddHandler;
import com.pjs.wafapp.handler.blockfqdn.BlockFqdnDeleteHandler;
import com.pjs.wafapp.handler.blockfqdn.BlockFqdnListHandler;
import com.pjs.wafapp.handler.blockfqdn.BlockFqdnModifyHandler;
import com.pjs.wafapp.handler.blockfqdn.BlockFqdnViewHandler;
import com.pjs.wafapp.handler.webserver.WebServerAddHandler;
import com.pjs.wafapp.handler.webserver.WebServerDeleteHandler;
import com.pjs.wafapp.handler.webserver.WebServerListHandler;
import com.pjs.wafapp.handler.webserver.WebServerModifyHandler;
import com.pjs.wafapp.handler.webserver.WebServerViewHandler;
import java.sql.Connection;
import java.sql.DriverManager;

public class App {

    Prompt prompt = new Prompt(System.in);
    WebServerDao webServerDao;
    BlockCidrDao blockCidrDao;
    BlockFqdnDao blockFqdnDao;

    MenuGroup mainMenu;

    App() {
        prepareDatabase();
        prepareMenu();
    }

    public static void main(String[] args) {
        System.out.println("[IP 차단 시스템]");
        new com.pjs.wafapp.App().run();
    }

    void prepareDatabase() {
        try {
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://db-ld2as-kr.vpc-pub-cdb.ntruss.com/wafdb", "wafadmin",
                "Bitcamp!@#123");

            //boardDao = new BoardDaoImpl(con, 1);
            //greetingDao = new BoardDaoImpl(con, 2);
            webServerDao = new WebServerDaoImpl(con);
            blockCidrDao = new BlockCidrDaoImpl(con);
            blockFqdnDao = new BlockFqdnDaoImpl(con);

        } catch (Exception e) {
            System.out.println("통신 오류!");
            e.printStackTrace();
        }
    }

    void prepareMenu() {
        mainMenu = MenuGroup.getInstance("WAF");

        MenuGroup webServerMenu = mainMenu.addGroup("웹서버");
        webServerMenu.addItem("웹서버 등록", new WebServerAddHandler(webServerDao, prompt));
        webServerMenu.addItem("웹서버 상세 조회", new WebServerViewHandler(webServerDao, prompt));
        webServerMenu.addItem("웹서버 정보 변경", new WebServerModifyHandler(webServerDao, prompt));
        webServerMenu.addItem("웹서버 삭제", new WebServerDeleteHandler(webServerDao, prompt));
        webServerMenu.addItem("웹서버 목록", new WebServerListHandler(webServerDao, prompt));

        MenuGroup cidrMenu = mainMenu.addGroup("IP차단");
        cidrMenu.addItem("차단 IP 등록", new BlockCidrAddHandler(blockCidrDao, prompt));
        cidrMenu.addItem("차단 IP 상세 조회", new BlockCidrViewHandler(blockCidrDao, prompt));
        cidrMenu.addItem("차단 IP 정책 변경", new BlockCidrModifyHandler(blockCidrDao, prompt));
        cidrMenu.addItem("차단 IP 정책 삭제", new BlockCidrDeleteHandler(blockCidrDao, prompt));
        cidrMenu.addItem("차단 IP 정책 목록", new BlockCidrListHandler(blockCidrDao, prompt));

        MenuGroup fqdnMenu = mainMenu.addGroup("URL차단");
        fqdnMenu.addItem("정책 등록", new BlockFqdnAddHandler(blockFqdnDao, prompt));
        fqdnMenu.addItem("정책 조회", new BlockFqdnViewHandler(blockFqdnDao, prompt));
        fqdnMenu.addItem("정책 변경", new BlockFqdnModifyHandler(blockFqdnDao, prompt));
        fqdnMenu.addItem("정책 삭제", new BlockFqdnDeleteHandler(blockFqdnDao, prompt));
        fqdnMenu.addItem("목록", new BlockFqdnListHandler(blockFqdnDao, prompt));
        //mainMenu.addItem("도움말", new HelpHandler(prompt));
    }

    void run() {
        while (true) {
            try {
                mainMenu.execute(prompt);
                prompt.close();
                break;
            } catch (Exception e) {
                System.out.println("예외 발생!");
            }
        }
    }

}
