/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pjs.wafapp;

import com.pjs.wafapp.dao.BlockCidrDao;
import com.pjs.wafapp.dao.mysql.BlockCidrDaoImpl;
import com.pjs.wafapp.handler.blockcidr.BlockCidrAddHandler;
import com.pjs.wafapp.handler.blockcidr.BlockCidrDeleteHandler;
import com.pjs.wafapp.handler.blockcidr.BlockCidrListHandler;
import com.pjs.wafapp.handler.blockcidr.BlockCidrModifyHandler;
import com.pjs.wafapp.handler.blockcidr.BlockCidrViewHandler;
import com.pjs.menu.MenuGroup;
import com.pjs.util.Prompt;
import java.sql.Connection;
import java.sql.DriverManager;

public class App {

    Prompt prompt = new Prompt(System.in);
    BlockCidrDao blockCidrDao;

    MenuGroup mainMenu;

    App() {
        prepareDatabase();
        prepareMenu();
    }

    public static void main(String[] args) {
        System.out.println("[IP 차단 시스템]");
        new com.pjs.wafapp.App().run();
    }

    void prepareDatabase() {
        try {
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://db-ld2as-kr.vpc-pub-cdb.ntruss.com/wafdb", "wafadmin",
                "Bitcamp!@#123");

            //boardDao = new BoardDaoImpl(con, 1);
            //greetingDao = new BoardDaoImpl(con, 2);
            blockCidrDao = new BlockCidrDaoImpl(con);
            //assignmentDao = new AssignmentDaoImpl(con);

        } catch (Exception e) {
            System.out.println("통신 오류!");
            e.printStackTrace();
        }
    }

    void prepareMenu() {
        mainMenu = MenuGroup.getInstance("WAF");

        MenuGroup assignmentMenu = mainMenu.addGroup("IP차단");
        assignmentMenu.addItem("정책 등록", new BlockCidrAddHandler(blockCidrDao, prompt));
        assignmentMenu.addItem("정책 조회", new BlockCidrViewHandler(blockCidrDao, prompt));
        assignmentMenu.addItem("정책 변경", new BlockCidrModifyHandler(blockCidrDao, prompt));
        assignmentMenu.addItem("정책 삭제", new BlockCidrDeleteHandler(blockCidrDao, prompt));
        assignmentMenu.addItem("목록", new BlockCidrListHandler(blockCidrDao, prompt));

        //mainMenu.addItem("도움말", new HelpHandler(prompt));
    }

    void run() {
        while (true) {
            try {
                mainMenu.execute(prompt);
                prompt.close();
                break;
            } catch (Exception e) {
                System.out.println("예외 발생!");
            }
        }
    }

}
